/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/tasks": {
    /** Get all tasks */
    get: operations["getTasks"];
    /** Create a new task */
    post: operations["createTask"];
  };
  "/tasks/{objectId}": {
    /** Get a task */
    get: operations["getTask"];
    /** Update a task */
    put: operations["updateTask"];
    /** Delete a task */
    delete: operations["deleteTask"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @enum {string} */
    success: "success";
    /** @enum {string} */
    fail: "fail";
    generic: boolean | Record<string, never> | number | string;
    /** Task */
    task: {
      title: string;
      description?: string;
      completed?: boolean;
      _id?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
  };
  responses: {
    /** @description 4XX Fail */
    genericFail: {
      content: {
        "application/json": {
          status?: components["schemas"]["fail"];
          data?: {
            errorCore?: string;
            message?: string;
            details?: components["schemas"]["generic"][];
          };
        };
      };
    };
  };
  parameters: {
    /** @description Object ID */
    objectId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Get all tasks */
  getTasks: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": {
            status?: components["schemas"]["success"];
            data?: {
              tasks?: components["schemas"]["task"][];
            };
          };
        };
      };
    };
  };
  /** Create a new task */
  createTask: {
    requestBody?: {
      content: {
        "application/json": {
          title: components["schemas"]["task"]["title"];
          description?: components["schemas"]["task"]["description"];
          completed?: components["schemas"]["task"]["completed"];
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": {
            status?: components["schemas"]["success"];
            data?: {
              task?: components["schemas"]["task"];
            };
          };
        };
      };
      "4XX": components["responses"]["genericFail"];
    };
  };
  /** Get a task */
  getTask: {
    parameters: {
      path: {
        objectId: components["parameters"]["objectId"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": {
            status?: components["schemas"]["success"];
            data?: {
              task?: components["schemas"]["task"];
            };
          };
        };
      };
      "4XX": components["responses"]["genericFail"];
    };
  };
  /** Update a task */
  updateTask: {
    parameters: {
      path: {
        objectId: components["parameters"]["objectId"];
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          title?: components["schemas"]["task"]["title"];
          description?: components["schemas"]["task"]["description"];
          completed?: components["schemas"]["task"]["completed"];
        };
      };
    };
    responses: {
      /** @description Updated */
      200: {
        content: {
          "application/json": {
            status?: components["schemas"]["success"];
            data?: {
              task?: components["schemas"]["task"];
            };
          };
        };
      };
      "4XX": components["responses"]["genericFail"];
    };
  };
  /** Delete a task */
  deleteTask: {
    parameters: {
      path: {
        objectId: components["parameters"]["objectId"];
      };
    };
    responses: {
      /** @description Deleted */
      200: {
        content: {
          "application/json": {
            status?: components["schemas"]["success"];
            data?: {
              task?: components["schemas"]["task"];
            };
          };
        };
      };
      "4XX": components["responses"]["genericFail"];
    };
  };
}
